import Head from 'next/head'
import { Inter } from '@next/font/google'
import { PetShop } from '../module';
import { SearchReservationProvider } from 'context';
import { Container } from 'components';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  return (
    <>
      <Head>
        <title>Pet Shop Waiting List</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container width="w-4/5">
        <SearchReservationProvider>
          <PetShop />
        </SearchReservationProvider>
      </Container>
    </>
  )
}
